{% set name = "wagtail-flexible-forms" %}
{% set version = "2.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/wagtail_flexible_forms-{{ version }}.tar.gz
  sha256: d03047559d074949f38ccb22fdecf66023cadfcba79cf278f3c87c4f52f6b658

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=65.0
    - pip
  run:
    - python >={{ python_min }}
    - wagtail >=3.0,<7

test:
  imports:
    - wagtail_flexible_forms
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Wagtail StreamField-based form builder.
  home: https://docs.coderedcorp.com/wagtail-flexible-forms
  dev_url: https://github.com/coderedcorp/wagtail-flexible-forms
  doc_url: https://docs.coderedcorp.com/wagtail-flexible-forms
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - rxm7706
