{% set name = "wagtail-flexible-forms" %}
{% set version = "2.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/wagtail_flexible_forms-{{ version }}.tar.gz
  sha256: 558401f14ee116887eeecb55d98e5b901c4455f32b7ccd1e235d8a0928121479

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=65.0
    - pip
  run:
    - python >={{ python_min }}
    - wagtail >=6.0,<8.0

test:
  imports:
    - wagtail_flexible_forms
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Wagtail StreamField-based form builder.
  home: https://docs.coderedcorp.com/wagtail-flexible-forms
  dev_url: https://github.com/coderedcorp/wagtail-flexible-forms
  doc_url: https://docs.coderedcorp.com/wagtail-flexible-forms
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - rxm7706
